### ISSUE TITLE
spaces in data file

### ISSUE THREAD

**Issue by aydindemircioglu** [aydindemircioglu/SVMBridge#13]
if the data file has spaces like "cover type.data" probably some wrapper will die.

**Comment by aydindemircioglu** [comment]
cannot be controlled directly, need to use 'bashExpand' to circumvent this problem.
need to add a  unit test for the prepackaged wrappers and then close this.

**Comment by aydindemircioglu** [comment]
this becomes now funny. i use ":::bashEscape" inside the wrappers.
devtools::check tells me that i do not need ":::".
but if a user removes the default packages and reloads them, he will
for sure need the :::?
one solutions would be possibly to add the ":::" if the wrappers get copied
from the R to the inst/wrapper directory-- an ugly solution.

**Comment by berndbischl** [comment]
if you need a function in the wrappers, export it. sorry, I did not want to complicate this.

**Comment by aydindemircioglu** [comment]
actually i'm more uncertain how to handle this altogether.
my bashescape routine is rather empty, only adding quotes.
this is not correct, it should actually escape all non-bash-characters
and this probably platform dependent. i'd hoped for a r routine that 
does exactly this conversion. do you happen to know such a function?

**Comment by berndbischl** [comment]
i only can remember this here, does that work for you?
https://stat.ethz.ch/R-manual/R-devel/library/base/html/shQuote.html

**Comment by aydindemircioglu** [comment]
for sure better than my hack, will replace my bashescape
and then there is no problem with the ::: anymore. thanks!
