### ISSUE TITLE
data.frame vs matrix

### ISSUE THREAD

**Issue by aydindemircioglu** [aydindemircioglu/SVMBridge#14]
currently we only take matrix, but probably, if a data.frame is given and can be simply converted into a matrix, we should do that.

**Comment by aydindemircioglu** [comment]
# #36 is a duplicate, so closing this now.

**Comment by berndbischl** [comment]
as you never said whether this issue actually relates to "x" or "y" i am not sure whether #35 is a the correct duplicate. actually only "x" should be a df, so the duplicate should be #35

**Comment by berndbischl** [comment]
but its still a duplicate :)
