### ISSUE TITLE
tilde is not expanded

### ISSUE THREAD

**Issue by aydindemircioglu** [aydindemircioglu/SVMBridge#15]
reading sparse data does not expand the tilde.
even worse, it crashes R. 
-so add a check if file can be opened and stop gracefully
-use the code from 
http://stackoverflow.com/questions/2924238/how-to-open-a-file-in-users-home-folder
to at least try to expand the tilde.

**Comment by HannaHouphouet** [comment]
readSparseData will now find tilde characters in given file paths and will manually expand it to the home directory of the logged user.

**Comment by aydindemircioglu** [comment]
did you test this on windows too?

**Comment by HannaHouphouet** [comment]
tilde characters are now correctly expanded on unix/windows systems for the functions trainSVM, testSVM, readSparseData, findSVMSoftware, findSVMWrapper. The user may use tilde characters in the path for the SVM binaries as well as for the path for the dataset. There exists a testthat case in test_SparseData: case #10
