### ISSUE TITLE
libsvm model read/write for binary models

### ISSUE THREAD

**Issue by aydindemircioglu** [aydindemircioglu/SVMBridge#18]
both, libsvm model read and write are yet only for binary data.
first we need to make sure that we can fully read and write the
binary models:
a) make sure that the libsvm.readmodel function reads all
the data from the model, even if it does not use them (e.g.
number of pos/neg support vectors). use the mnist.binary.model
file from the tests/data folder
b) write a small testthat-test that first makes sure that reading
a model and writing a model for binary data does work, i.e.
read/write/read of mnist.binary.model will work.

**Comment by HannaHouphouet** [comment]
Done. test #7 in test_sparseData.R
