### ISSUE TITLE
libsvm model read/write for multiclass

### ISSUE THREAD

**Issue by aydindemircioglu** [aydindemircioglu/SVMBridge#19]
make sure that libsvm model read and write does work with multiclass model
files, e.g. with mnist.model. 
a) enhance the libsvm.readmodel function to allow for multiclass models. 
b) enhance the libsvm.writemodel to allow for multiclass models.
c) write a test that read/writes/reads mnist.model.

**Comment by HannaHouphouet** [comment]
Works partly. There are two values which are defined during the training operation. Thus these two values (total_sv, nr_sv) cannot been read out by the readSparseData function.

**Comment by aydindemircioglu** [comment]
this is already done together with a unittest.
