### ISSUE TITLE
testSVM should auto-detect method

### ISSUE THREAD

**Issue by aydindemircioglu** [aydindemircioglu/SVMBridge#20]
if testSVM does not obtain any method=.. parameter,
it should look at the object it got.
all training objects know their method.
but if method is specified, it should not autodetect
and use, what the predictor for the method specified.

**Comment by aydindemircioglu** [comment]
you can use the three easy if-checks from createFromFile in
https://github.com/aydindemircioglu/SharkSVM/blob/master/src/DataModels/SVMDataModelFactory.cpp

**Comment by HannaHouphouet** [comment]
The auto detect, in case there is no method given, works for testSVM.
