### ISSUE TITLE
Precision of written files

### ISSUE THREAD

**Issue by HannaHouphouet** [aydindemircioglu/SVMBridge#22]
There is a problem with the precision of writeSparseData function. In certain cases the written output will differ in matters of precision e.g. 0.422130000001 or 0.422129999999 instead of 0.42213. I've tried to  retrieve the needed precision for each value on the fly while writing the data which worked for datasets like sparse.data but didn't for datasets like protein and poker.

**Comment by aydindemircioglu** [comment]
probably unavoidable for now.
