### ISSUE TITLE
trainSVM / testSVM: trainDataFile, docs

### ISSUE THREAD

**Issue by berndbischl** [aydindemircioglu/SVMBridge#34]
Please explain in the docs what format is expected for the file. 
I am guessing 

a) you basically dont care, as you simple pass it on to the binary. please say so in the docs.
b) but currently all of these support libsvm sparse format. please also say so in the docs. 
for the provided solvers it would be nice to have a little table to see what they support.

**Comment by aydindemircioglu** [comment]
-added a paragraph to in the data section of the tutorial chapter.
-added a row in the table of the prepackaged wrappers in the corresponding chapter. (all support LIBSVM expect LASVM, which supports a binary and split file format-- probably not that useful)
