### ISSUE TITLE
hide your internal functions

### ISSUE THREAD

**Issue by berndbischl** [aydindemircioglu/SVMBridge#38]
you seem to export everything. 

you certainly dont want stuff like bashEscape in the public interface of your package?

**Comment by aydindemircioglu** [comment]
most of the stuff is really necessary (read: convenient) when writing one's own wrapper,
which is still the number 1 purpose of the SVMBridge.
but you are right that bashEscape can be "not exported", as it can still be called by :::
when a user who wants to write his own wrapper.
will fix it and check also check the other functions.

**Comment by berndbischl** [comment]
OK. What is useful in wriiting the wrappers SHOULD be exported, and documented.
Simply look at the NAMESPACE. 

If you think there is no "useless" internal stuff in there (for endusers) just close here.

**Comment by aydindemircioglu** [comment]
reduced the amount of exported functions. might have missed one or two, will fix along the way.
