### ISSUE TITLE
svmbridge or mlbridge?

### ISSUE THREAD

**Issue by berndbischl** [aydindemircioglu/SVMBridge#4]
is there actaully anything specific in the software for SVMs?

or could it be used to connect, other ML command line algos as well?

because if so, it would be great.

just asking.

**Comment by aydindemircioglu** [comment]
technically, if the general learner can be divided in two steps,
training and test, can be called via command line, and can handle
SVM sparse data, this should work. for non-sparse data, e.g. CSV,
one needs to extend the bridge itself. obviously, one also needs
some kind of model-from-file and model-to-file routines for any
learner, as well as similar functions for the predictions.

having two steps seems a restriction, but some learners might be
still be put into this rigid corset, as the train function is defined
by the wrapper. e.g. for DCSVM, i generate a matlab script
and call that.  ISSVM has a five executables, one can still divide
them into a train and test step. 

so yes, basically more learners could be included, but for now
i stick with SVMBridge to get this done somewhere within the
next months ;)
