### ISSUE TITLE
bug in testSVM 

### ISSUE THREAD

**Issue by berndbischl** [aydindemircioglu/SVMBridge#43]
I certainly would like to predict on newdata without having to provide the labels

```
> p = testSVM(model = m$model, testDataX = x)
Error in testSVM(model = m$model, testDataX = x) : 
  Assertion on 'testDataY' failed: Must be of type 'matrix', not 'NULL'
```

**Comment by berndbischl** [comment]
doc and unit test this

**Comment by aydindemircioglu** [comment]
this is not as  easy as it might sound, as practically all SVMs will need a (dummy) label for doing prediction. if i allow the labels y to be optional, this poses no problem for data in memory (just create dummy labels)-- but for data that is already on disk and also has no label, this would mean that i first have to read the data into memory, add a dummy label and write that back to disk. to avoid overcomplication of this method, i will add now a predictSVM method.

**Comment by berndbischl** [comment]
that would be good. it definitely is a needed feature.

**Comment by aydindemircioglu** [comment]
added predictSVM and some tests (but only OS-specific ones).
